[env:micro]
platform = atmelavr
board = micro
framework = arduino

; Serial monitor settings
monitor_speed = 115200

; Libraries
lib_deps = 
    https://github.com/pololu/lsm6-arduino.git
    https://github.com/pololu/lis3mdl-arduino.git