imu_filter_node:
  ros__parameters:
    use_mag: true
    publish_tf: false
    world_frame: enu
    
    # Output frame should be base_link for robot odometry
    fixed_frame: base_link
    
    # Topics
    imu_topic: /imu/data_raw
    mag_topic: /imu/mag
    
    gain: 0.1
    zeta: 0.001
    orientation_stddev: 0.05