teleop_twist_joy_node:
  ros__parameters:
    axis_linear.x: 1         # Left stick vertical
    axis_linear.y: 0         # Left stick horizontal (Strafing)
    axis_angular.yaw: 3      # Right stick horizontal (Rotation)
    scale_linear.y: 0.5      # Speed for sideways movement
    scale_linear.x: 0.5
    scale_angular.yaw: 1.0